Se modifica el template

diff --git a/.github/workflows/functions-deploy-action.yml b/.github/workflows/functions-deploy-action.yml
--- a/.github/workflows/functions-deploy-action.yml
+++ b/.github/workflows/functions-deploy-action.yml
@@ -15,6 +15,8 @@ on:
     secrets:
       AZ_CLIENT_ID:
         required: true
+      AZ_CLIENT_SECRET:
+        required: true
       AZ_TENANT_ID:
         required: true
       AZ_SUBSCRIPTION_ID:
@@ -77,7 +79,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     permissions:
-      id-token: write
       contents: read
     environment:
       name: ${{ inputs.environment }}
@@ -100,6 +101,7 @@ jobs:
           
           # Secrets de Azure (Autenticación) - Verificar primero porque se necesitan para el login
           if [ -z "${{ secrets.AZ_CLIENT_ID }}" ]; then echo "❌ ERROR: La variable AZ_CLIENT_ID no está definida. Abortando despliegue."; exit 1; else echo "✅ AZ_CLIENT_ID detectada correctamente."; fi
+          if [ -z "${{ secrets.AZ_CLIENT_SECRET }}" ]; then echo "❌ ERROR: La variable AZ_CLIENT_SECRET no está definida. Abortando despliegue."; exit 1; else echo "✅ AZ_CLIENT_SECRET detectada correctamente."; fi
           if [ -z "${{ secrets.AZ_TENANT_ID }}" ]; then echo "❌ ERROR: La variable AZ_TENANT_ID no está definida. Abortando despliegue."; exit 1; else echo "✅ AZ_TENANT_ID detectada correctamente."; fi
           if [ -z "${{ secrets.AZ_SUBSCRIPTION_ID }}" ]; then echo "❌ ERROR: La variable AZ_SUBSCRIPTION_ID no está definida. Abortando despliegue."; exit 1; else echo "✅ AZ_SUBSCRIPTION_ID detectada correctamente."; fi
           
@@ -117,11 +119,14 @@ jobs:
           echo "✅ Todos los secrets están presentes. Procediendo con el login a Azure..."
 
       - name: Login to Azure
-        uses: azure/login@v2
-        with:
-          client-id: ${{ secrets.AZ_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZ_TENANT_ID }}
-          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
+        run: |
+          az login --service-principal \
+            --username "${{ secrets.AZ_CLIENT_ID }}" \
+            --password "${{ secrets.AZ_CLIENT_SECRET }}" \
+            --tenant "${{ secrets.AZ_TENANT_ID }}" \
+            --output none
+          
+          az account set --subscription "${{ secrets.AZ_SUBSCRIPTION_ID }}"
 
       - name: Sincronizar Application Settings desde GitHub Secrets a Azure Function
         run: |
